name: wp_swarm

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    command:
      --api=true
      --log.level=INFO
      --providers.docker
      --providers.docker.exposedbydefault=false
      --providers.file.directory=/etc/traefik
      --entrypoints.webhttp.address=:80
      --entrypoints.webhttps.address=:443
      --entrypoints.webhttps.http.tls=true
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - ./traefik/config:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOST_URL}`)"
      - "traefik.http.routers.dashboard.entrypoints=webhttps"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TREAFIK_USERNAME}:${TRAEFIK_ENCRY_PW}"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: |
      --interval 30
      --label-enable=true
  webserver:
    image: jwhangbo/v2:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`jwwhangbo.com`)"
      - "traefik.http.routers.webserver.entrypoints=webhttps"
      - "traefik.http.services.webserver.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENVIRONMENT_TYPE', '${ENVIRONMENT:-production}');
        define('WP_DEVELOPMENT_MODE', '${WP_DEVELOPMENT_MODE:-false}');
        define('HEADLESS_SECRET', '${HEADLESS_SECRET}');
        define('HEADLESS_URL', '${HEADLESS_URL}');
        define('GRAPHQL_JWT_AUTH_SECRET_KEY', '${GRAPHQL_JWT_AUTH_SECRET_KEY}');
        define('GRAPHQL_JWT_AUTH_CORS_ENABLE', true);
        define('WP_SITEURL', '${WP_SITEURL}');
        define('WP_HOME', '${WP_HOMEURL}');
        @ini_set('max_execution_time', '120');
        @ini_set( 'upload_max_size' , '128M' );
        @ini_set( 'post_max_size', '128M');
    volumes:
      - wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${WP_HOST_URL}`)"
      - "traefik.http.routers.wordpress.entrypoints=webhttps"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
